= hexproc(1)
Philip Roman
include::../VERSION[]
:doctype: manpage
:revdate: 2019-08-17

== Name

hexproc - hexadecimal preprocessor for building binary files or hexdumps

== Synopsis

`*hexproc* [_OPTION_|_FILE_]`

== Options

*-v, --version*::
	Prints the program version and exits

*-h, --help*::
	Prints a brief help message and exits

== Description

Hexproc is a tool for building hex files. The input file
(or `stdin`, if no file given) is processed and then
written to `stdout`.

Hexproc is meant to be used as part of a pipeline and
therefore does not implement many features which are
provided by other processing tools.

It is recommended to use a text preprocessor (such as
`cpp` or `m4`) before feeding the input to `hexproc` as
`hexproc` does not provide macros or file inclusion.

If you wish to build a binary file from the output of
`hexproc`, use `xxd -p -r` (`-r` is for reverse hexdump
and `-p` is for plain format).

== Syntax

Hexproc input consists of the following tokens:

*strings*::
	Quoted ASCII text is converted to bytes and replaced
	with hexadecimal octets

*octets*::
	Two hexadecimal digits (seperated from other tokens by
	whitespace) are outputted as-is

*comments*::
	End-of-line comments are created using `#`, `;` or `//`.
	You can also add block comments starting with `/*` and
	ending with `*/`.

*expressions*::
	Expressions are not standalone constructs, they are used
	in forming *labels*. Expressions can be described using
	the following grammar (operator precedence is as expected,
	but you will still need spaces around operators):

	exp ::= LabelName
	exp ::= Decimal
	exp ::= Hexadecimal
	exp ::= exp + exp
	exp ::= exp - exp
	exp ::= exp * exp
	exp ::= exp / exp
	exp ::= exp ^ exp

*labels*::
	A line in form of `KEY: EXPRESSION` is called a _label_
	(`EXPRESSION` may be omitted). Labels act as global variables.
	When encountering a label, `KEY` is mapped to the `EXPRESSION`
	or the current byte offset, if no value provided. `KEY` may
	contain numbers, letters, underscores and dots. Existing
	labels may not be redefined. It is allowed to refer to a
	label name before the corresponding label has been declared.

*formatters*::
	An expression in form of `[TYPE]LABELNAME` or `[TYPE](EXPRESSION)`
	is called a _formatter_. `TYPE` may be an integer denoting the
	number of bytes to use or a _type name_, such as "int64" or "float",
	which is replaced with the size of that type (but may also
	have influence on the representation of the value).

Leading and trailing whitespace is ignored.

Hexproc maps lines one-to-one so that line numbers
are preserved.

== Type Names
The following identifiers may be used as type names:

* int64, int32, int16, int8 - fixed size types
* long, int, short, byte - synonymous with fixed size types
* ieee754_single, ieee754_double - IEEE 754 single and double precision floating point types
* float, double - synonymous with above floating point types

== See Also
xxd(1), cpp(1)
